[package]
name = "simple-rss"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.28", features = ["event-stream"] }
anyhow = "1.0"
ratatui = "0.29"
textwrap = "0.16"
tokio = { version = "1.44", features = ["full"] }
futures = "0.3.31"
